### ISSUE TITLE
Review return value of $google_id in `src/Shipping/ZoneLocationsParser.php` - Null value causes fatal error in some cases

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/google-listings-and-ads#1910]
5997199-zen

Merchant entered some countries in their shipping zone: https://d.pr/i/ZUcZp2

Return value null from:

https://github.com/woocommerce/google-listings-and-ads/blob/592e0cb62bf6e7301506fd4285b141d052308986/src/Shipping/ZoneLocationsParser.php#L77

is causing a fatal error on step 3 of onboarding screen: 

```
2023-02-28T08:52:42+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\GoogleListingsAndAds\Shipping\ShippingLocation::__construct() must be of the type int, null given, called in /home2/a2knozmd/public_html/wp-content/plugins/google-listings-and-ads/src/Shipping/ZoneLocationsParser.php on line 78 and defined in /home2/a2knozmd/public_html/wp-content/plugins/google-listings-and-ads/src/Shipping/ShippingLocation.php:48
Stack trace:
#0 /home2/a2knozmd/public_html/wp-content/plugins/google-listings-and-ads/src/Shipping/ZoneLocationsParser.php(78): Automattic\WooCommerce\GoogleListingsAndAds\Shipping\ShippingLocation->__construct(NULL, 'US', 'AA', NULL)
#1 /home2/a2knozmd/public_html/wp-content/plugins/google-listings-and-ads/src/Shipping/ShippingZone.php(144): Automattic\WooCommerce\GoogleListingsAndAds\Shipping\ZoneLocationsParser->parse(Object(WC_Shipping_Zone))
#2 /home2/a2knozmd/public_html/wp-content/ in /home2/a2knozmd/public_html/wp-content/plugins/google-listings-and-ads/src/Shipping/ShippingLocation.php on line 48
```

I am assuming the null value comes from here: 

https://github.com/woocommerce/google-listings-and-ads/blob/592e0cb62bf6e7301506fd4285b141d052308986/src/Google/GoogleHelper.php#L1335

There are other functions as well on the same file: `find_country_id_by_code()`  `find_subdivision_code_by_id()` that may return a null value for some countries.

I am not sure which country code is causing this issue here but I was able to replicate it on my test site by copying the same countries present in merchant's shipping zone.

**Comment by kaushikasomaiya** [comment]
It appears to be with locations: "Armed Forces" (AA,AE,AP)

**Comment by mikkamp** [comment]
I can reproduce this locally be adding the location `Armed Forces (AA)` to a US shipping method, and calling the endpoint:
`https://domain.test/wp-json/wc/gla/mc/shipping/rates/suggestions?country_codes[]=US`

```
[28-Feb-2023 12:54:36 UTC] PHP Fatal error:  Uncaught TypeError: Automattic\WooCommerce\GoogleListingsAndAds\Shipping\ShippingLocation::__construct(): Argument #1 ($google_id) must be of type int, null given, called in google-listings-and-ads/src/Shipping/ZoneLocationsParser.php on line 78 and defined in google-listings-and-ads/src/Shipping/ShippingLocation.php:48

**Comment by kaushikasomaiya** [comment]
6076368-zen
